# Generated by Django 3.1.7 on 2021-08-14 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subreddit',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='downs',
            field=models.ManyToManyField(blank=True, related_name='post_downs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='ups',
            field=models.ManyToManyField(blank=True, related_name='post_ups', to=settings.AUTH_USER_MODEL),
        ),
    ]
