# Generated by Django 3.1.7 on 2021-08-16 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddit', '0002_auto_20210814_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
